import "./globals.css";
import type { Metadata } from "next";
import AuthProvider from "./contexts/AuthContext";
import PageProvider from "./contexts/AppContext";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import Loading from "./pages/homePage/introduce/Loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <PageProvider>
        <AuthProvider>
          <body className={inter.className}>{children}</body>
        </AuthProvider>
      </PageProvider>
    </html>
  );
}
